# Generated by Django 3.1.5 on 2021-01-06 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmergame', '0005_annualcrop_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annualcrop',
            old_name='sell_price',
            new_name='crop_sell_price',
        ),
        migrations.RenameField(
            model_name='annualcrop',
            old_name='buy_price',
            new_name='seed_price',
        ),
    ]
