# Generated by Django 3.1.5 on 2021-01-05 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmergame', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='costs',
        ),
        migrations.AddField(
            model_name='animal',
            name='buy_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='animal',
            name='sell_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='animal',
            name='benefits',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='OwnAnimal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_owned', models.IntegerField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmergame.animal')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmergame.farm')),
            ],
        ),
        migrations.AddField(
            model_name='farm',
            name='animals',
            field=models.ManyToManyField(through='farmergame.OwnAnimal', to='farmergame.Animal'),
        ),
    ]
