# Generated by Django 3.1.5 on 2021-01-06 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmergame', '0006_auto_20210106_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annualcrop',
            old_name='crop_sell_price',
            new_name='sell_price',
        ),
    ]
